services:
  postgres:
    image: postgres:16-alpine
    container_name: a4_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: a4
      POSTGRES_PASSWORD: a4pass
      POSTGRES_DB: a4_telemetry
    ports:
      - "5432:5432"
    volumes:
      - a4_pgdata:/var/lib/postgresql/data

volumes:
  a4_pgdata:
